services:
  loginmanager:
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
    depends_on:
      - db
    build:
      context: ./LoginManager
      dockerfile: ./LoginManagerAPI/Dockerfile
    container_name: loginmanager
  mailconfirmation:
    container_name: mailconfirmation
    depends_on:
      - db
    environment:
      MAIL_PASSWORD: 
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
    build:
      context: ./MailConfirmation
      dockerfile: ./Dockerfile
      
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: shfdismini
    ports:
      - 5432:5432
volumes:
  pgdata: