version: "3.9"
services:
  loginmanager:
    build:
      context: ./LoginManager
      dockerfile: ./LoginManager/LoginManagerAPI/Dockerfile
    container_name: loginmanager
  mailconfirmation:
    
    container_name: mailconfirmation
    environment:
      MAIL_PASSWORD: 
    build:
      context: ./MailConfirmation
      dockerfile: ./MailConfirmation/Dockerfile
      
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: shfdismini
volumes:
  pgdata:
